{"name": "test_Verify_error_displayed_when_invalid_username_entered[data1]", "status": "passed", "attachments": [{"name": "data was entered", "source": "4a3a7684-e058-4869-890c-cfc0a4522f62-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "db3d8213-9a39-4150-bd12-c51d2b00e35f-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['09654257082']"}], "start": 1623560815113, "stop": 1623560823711, "uuid": "0326d3ff-1c12-47a8-a02b-5d502992ec5d", "historyId": "96061be290c47b5b221f14a7d6d54183", "testCaseId": "9771d5a1960ba0955ca6e6cfdc6c04ae", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_username_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "HazelYu"}, {"name": "thread", "value": "9388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}