{"name": "test_Verify_error_displayed_when_invalid_username_entered[data0]", "status": "passed", "attachments": [{"name": "data was entered", "source": "b97fa762-f79a-4a59-9973-fa4c90abc951-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "939d84c1-2b97-4d78-b64b-3f984749400f-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['notexist@mail.com']"}], "start": 1595949911257, "stop": 1595949923796, "uuid": "a4d24478-ef0e-4635-9dff-282de0a62628", "historyId": "a79a86d16a4d43e77cc7c62e2e1d8c05", "testCaseId": "9771d5a1960ba0955ca6e6cfdc6c04ae", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_username_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "LAPTOP-45C52QUA"}, {"name": "thread", "value": "6008-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}