{"name": "test_Verify_error_displayed_when_invalid_username_entered[data2]", "status": "passed", "attachments": [{"name": "data was entered", "source": "1a01a70d-5e73-4ca0-8ca8-1dbc09de5633-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "aecf7807-7dbc-4dcd-ad9c-5d5d83f4c994-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['%@&*!']"}], "start": 1595949333516, "stop": 1595949344564, "uuid": "4bbf9223-7ac9-4295-aadb-2362d61914d7", "historyId": "e21aed30c34cc1a78d85dfb606e7895c", "testCaseId": "9771d5a1960ba0955ca6e6cfdc6c04ae", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_username_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "LAPTOP-45C52QUA"}, {"name": "thread", "value": "1476-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}