{"name": "test_Verify_error_displayed_when_invalid_username_entered[data1]", "status": "passed", "attachments": [{"name": "data was entered", "source": "76f72f98-3300-4bb3-9dab-0770c5bab9e1-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "5fbdd9d0-81db-4c77-9cce-1949735a4c52-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['09654257082']"}], "start": 1595949324294, "stop": 1595949333507, "uuid": "50c414f2-06fc-4caf-9e9b-7291edee6c25", "historyId": "96061be290c47b5b221f14a7d6d54183", "testCaseId": "9771d5a1960ba0955ca6e6cfdc6c04ae", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_username_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "LAPTOP-45C52QUA"}, {"name": "thread", "value": "1476-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}