{"name": "test_Verify_error_displayed_when_invalid_username_entered[data2]", "status": "passed", "attachments": [{"name": "data was entered", "source": "d8e32d08-071f-47f1-ae40-1e40f501911c-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "ae26c4ee-b423-4250-84ff-787794dab7fd-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['%@&*!']"}], "start": 1595949935771, "stop": 1595949944178, "uuid": "47cfadc7-fe61-414f-ab90-a4deaa02dd6f", "historyId": "e21aed30c34cc1a78d85dfb606e7895c", "testCaseId": "9771d5a1960ba0955ca6e6cfdc6c04ae", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_username_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "LAPTOP-45C52QUA"}, {"name": "thread", "value": "6008-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}