{"name": "test_Verify_error_displayed_when_invalid_username_entered[data1]", "status": "passed", "attachments": [{"name": "data was entered", "source": "1fa869c3-5ca6-47f5-b95c-0a2bca0c9617-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "81d8203b-c963-4567-b6ff-79ed909ba495-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['09654257082']"}], "start": 1595949923801, "stop": 1595949935762, "uuid": "fa870a31-9350-4ca2-be24-9ce7c1199de2", "historyId": "96061be290c47b5b221f14a7d6d54183", "testCaseId": "9771d5a1960ba0955ca6e6cfdc6c04ae", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_username_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "LAPTOP-45C52QUA"}, {"name": "thread", "value": "6008-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}